Multibeam Sonar Migration Template
KMOU-IOES/dave pull request #15
Opened 2024-08-19 01:01 UTC by woensug-choi

This is to fastforward the effort the migration of the Muiltibeam Sonar plugin.

Notion note related to this is at https://yeongdocat.notion.site/Multibeam-Sonar-Plugin-Migration-Memo-3a98b778e87a419b9adf32a88d78814c?pvs=4

## Progress (Check date of the update, I am updating this as I progress)
- [x] Copy and rename the generic dvl plugin of gazebo offical https://github.com/gazebosim/gz-sim/tree/gz-sim8/src/systems/dvl
- [x] Sample world file including system plugin and the sensor plugin
       `ros2 launch dave_demos dave_world.launch.py world_name:=dave_multibeam_sonar verbose:=true`
- [x] Launch system with sensor sample in empty world with objects
       `ros2 launch dave_demos multibeam_sonar_standalone.launch.py x:=4.0 z:=0.5 Y:=3.14`
- [x] Insert codes of GPU Lidar to publish `point cloud`
- [ ] Add tag handles to read multibeam sonar parameters from SDF
- [ ] Construct a dataset to pipeline into CUDA code
- [ ] Insert CUDA code wrapper function
- [ ] Conditional CMAKE to check wether the machine has CUDA building and runtime library

## Leftover
- The PointCloud GUI viewer inside Gazebo does not work. Not fully understood why
   - https://github.com/gazebosim/gz-gui/pull/346
   - Not sure what `Float_V` is for

2025-06-26 05:13 UTC, hmoyen commented
# PR: Multibeam Sonar Plugin Migration

To test this branch, please follow the [Multibeam Sonar README](https://github.com/IOES-Lab/dave/blob/sonar_ws_progress/gazebo/dave_gz_multibeam_sonar/README.md).

In summary, the plugin uses a custom Gazebo plugin based on a ray sensor and a custom DVL plugin to generate a point cloud. From this point cloud, a depth image is created and used as input for sonar image computation in the CUDA code. After the CUDA calculations are completed, the raw sonar data, sonar image, and normal image are published as ROS 2 topics. The sonar image can then be visualized in RViz 2. The example setup uses parameters for the **BlueView P900** in a sample world.

---

###  Key Features

- Custom **Gazebo plugin** for multibeam sonar (to include in sonar SDF models)
- Multibeam **Sonar System plugin** (to include in world files)
- Sample world: `dave_multibeam_world.world`
- Sample sonar: `blueview_p900`
- Demo setup with:
  - Launch file
  - RViz config
  - Script to plot raw sonar data

---

###  From the README, you should be able to:

- ✅ Run the demo
- ✅ Create your own sonar model
- ✅ Create your own world
- ✅ Launch the world + sonar together
- ✅ Visualize point cloud and sonar image in RViz2

---

Let me know of any issues

2025-07-02 00:47 UTC, rakeshv24 requested changes
@hmoyen I have shared my thoughts and suggestions. Please take a look and let me know if you need any further clarifications on any of the comments.

Overall, great job with the migration! :D

2025-07-02 00:47 UTC, rakeshv24 commented on build/.built_by
build folder should not exist

2025-07-02 00:47 UTC, rakeshv24 commented on build/COLCON_IGNORE
same as above

2025-07-02 00:47 UTC, rakeshv24 commented on build/dave_gz_sensor_plugins/colcon_build.rc
same as above

2025-07-02 00:47 UTC, rakeshv24 commented on examples/dave_demos/launch/dave_sensor.launch.py
Conflict between `debug` and `verbose`. It was originally designed such that if `debug=true`, then the user can set the verbosity level by specifying a number under the variable `verbose`. One suggestion would be to change `verbose` to `verbosity_level` and keep everything else as is.

2025-07-02 00:47 UTC, rakeshv24 commented on examples/dave_demos/launch/multibeam_sonar_standalone.launch.py
Let's remove this because we can launch the sonar sensor from `dave_sensor.launch.py`

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/README.md
Specify that NVIDIA Graphics Card with CUDA compatibility is required to work with the sonar plugin.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +/*
Add your name to the authors list here

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +#include <gz/math/Vector2.hh>
Is there a need for both Vector2 and Vector3?

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +class MultibeamSonarSensor::Implementation
Why not move this to the header file as this primarily contains declarations only? It is also a good practice to group the different access specifiers (public, private, etc).

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +  cv::Mat point_cloud_image_;
Follow correct and consistent naming conventions. Typically only private variables have an underscore as prefix or suffix.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +  cv::Mat point_cloud_normal_image_;
same as above

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.hh
> +
Make sure the imports are not redundant between this file and the main .cc file as this file will be imported there.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.hh
> +public:
Group the access specifiers for code cleanup.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_demo/launch/__pycache__/multibeam_sonar_demo.launch.cpython-312.pyc
cache files (.pyc) should be removed. Please modify .gitignore accordingly

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_demo/launch/multibeam_sonar_demo.launch.py
> +#
Update authorship

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_system/CMakeLists.txt
> +
Remove the commented out part if not required.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_system/package.xml
> +  <!-- <build_depend>dave_interfaces</build_depend>
remove these if not required

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/CMakeLists.txt
> +# find_package(CUDAToolkit QUIET)
Remove this if not required.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/MultibeamSonarSystem.hh
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/MultibeamSonar.hh
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/depth_camera.hh
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/sea_pressure_sensor.hh
do a git rebase to resolve this.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/package.xml
> +  <!-- <build_depend>marine_acoustic_msgs</build_depend>
remove if not required.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/MultibeamSonar.cc
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/MultibeamSonarSystem.cc
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/PointCloudUtil.cc
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/PointCloudUtil.hh
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/depth_camera.cc
Remove this file if it is no longer required as sonar has its own package.

2025-07-02 00:47 UTC, rakeshv24 commented on gazebo/dave_gz_sensor_plugins/src/UnderwaterCamera.cc
Rebase to resolve this

2025-07-02 00:47 UTC, rakeshv24 commented on install/.colcon_install_layout
Install directory should not be pushed. Please remove and update .gitignore

2025-07-02 00:47 UTC, rakeshv24 commented on install/COLCON_IGNORE
Install directory should not be pushed. Please remove and update .gitignore

2025-07-02 00:47 UTC, rakeshv24 commented on install/_local_setup_util_ps1.py
Install directory should not be pushed. Please remove and update .gitignore

2025-07-02 00:47 UTC, rakeshv24 commented on install/_local_setup_util_sh.py
Install directory should not be pushed. Please remove and update .gitignore

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/colcon-core/packages/dave_gz_sensor_plugins
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/dave_gz_sensor_plugins/package.bash
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/dave_gz_sensor_plugins/package.dsv
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/dave_gz_sensor_plugins/package.ps1
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/dave_gz_sensor_plugins/package.sh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/dave_gz_sensor_plugins/share/dave_gz_sensor_plugins/package.zsh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/local_setup.bash
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/local_setup.ps1
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/local_setup.sh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/local_setup.zsh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/setup.bash
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/setup.ps1
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/setup.sh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on install/setup.zsh
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on log/COLCON_IGNORE
Log folder should not be pushed as well. Remove and update .gitignore

2025-07-02 00:47 UTC, rakeshv24 commented on log/build_2024-08-15_09-10-19/events.log
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on log/latest
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on log/build_2024-08-15_09-10-19/logger_all.log
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on log/latest_build
Same as above

2025-07-02 00:47 UTC, rakeshv24 commented on models/dave_worlds/worlds/dvl_world.world
Rebase to resolve this

2025-07-02 00:47 UTC, rakeshv24 commented on models/dave_worlds/worlds/multibeam_sonar_tutorial.world
There are two world files for multibeam sonar. Merge them if there is no difference.

2025-07-02 00:47 UTC, rakeshv24 commented on models/dave_worlds/worlds/new_dvl.world
Rebase to resolve.

2025-07-02 00:47 UTC, rakeshv24 commented on models/dave_robot_models/launch/upload_robot.launch.py
Double check if this change is required.

2025-07-02 02:27 UTC, hmoyen commented on build/.built_by
Deleted!

2025-07-02 02:46 UTC, hmoyen commented on examples/dave_demos/launch/dave_sensor.launch.py
Changed it. 
`verbosity_level` : Set verbosity, where <= 0: No output, 1: Error messages, 2: Error and warning messages, 3: Error, warning, and info messages, >= 4: Error, warning, info, and debug messages.  Default is 1.
`debug`:  Flag to enable the gazebo debug flag. Default is false.

2025-07-02 02:46 UTC, hmoyen commented on examples/dave_demos/launch/multibeam_sonar_standalone.launch.py
Removed

2025-07-02 02:48 UTC, hmoyen commented on log/latest_build
Removed

2025-07-02 02:50 UTC, hmoyen commented on models/dave_worlds/worlds/multibeam_sonar_tutorial.world
Removed `multibeam_sonar_tutorial.world.`

2025-07-02 02:53 UTC, hmoyen commented on models/dave_worlds/worlds/dvl_world.world
Updated with ros2 branch.

2025-07-02 02:56 UTC, hmoyen commented on models/dave_robot_models/launch/upload_robot.launch.py
Changed to the ros2 branch file version.

2025-07-02 02:58 UTC, hmoyen commented on models/dave_worlds/worlds/new_dvl.world
Updated with ros2 branch.

2025-07-02 03:08 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/README.md
Added the system requirement to the README.

2025-07-02 03:11 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +/*
Added authors list to file.

2025-07-02 03:15 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +#include <gz/math/Vector2.hh>
Both are used in the source code, specifically in the acoustic beams calculations.

2025-07-02 04:04 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +  cv::Mat point_cloud_image_;
Solved.

2025-07-02 04:04 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +  cv::Mat point_cloud_normal_image_;
Solved.

2025-07-02 04:07 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.hh
> +
Reorganized headers.

2025-07-02 04:15 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.hh
> +public:
Solved.

2025-07-02 04:16 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_demo/launch/__pycache__/multibeam_sonar_demo.launch.cpython-312.pyc
Removed.

2025-07-02 04:17 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_demo/launch/multibeam_sonar_demo.launch.py
> +#
Solved.

2025-07-02 04:19 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +class MultibeamSonarSensor::Implementation
Reorganized headers.

2025-07-02 04:19 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_system/CMakeLists.txt
> +
Removed.

2025-07-02 04:19 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar_system/package.xml
> +  <!-- <build_depend>dave_interfaces</build_depend>
Removed.

2025-07-02 04:22 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/CMakeLists.txt
> +# find_package(CUDAToolkit QUIET)
Removed.

2025-07-02 04:23 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/MultibeamSonarSystem.hh
Removed.

2025-07-02 04:23 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/MultibeamSonar.hh
Removed.

2025-07-02 04:24 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/depth_camera.hh
Removed.

2025-07-02 04:25 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/include/dave_gz_sensor_plugins/sea_pressure_sensor.hh
Updated with ros2 branch.

2025-07-02 04:26 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/package.xml
> +  <!-- <build_depend>marine_acoustic_msgs</build_depend>
Removed.

2025-07-02 04:26 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/MultibeamSonarSystem.cc
Removed.

2025-07-02 04:26 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/MultibeamSonar.cc
Removed.

2025-07-02 04:26 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/PointCloudUtil.cc
Removed.

2025-07-02 04:27 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/PointCloudUtil.hh
Removed.

2025-07-02 04:27 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/depth_camera.cc
Removed.

2025-07-02 04:28 UTC, hmoyen commented on gazebo/dave_gz_sensor_plugins/src/UnderwaterCamera.cc
Updated with ros2 branch.

2025-07-02 13:51 UTC, rakeshv24 commented on examples/dave_demos/launch/dave_sensor.launch.py
Thank you!

2025-07-02 13:51 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/MultibeamSonarSensor.cc
> +#include <gz/math/Vector2.hh>
Sounds good.

2025-07-02 14:09 UTC, rakeshv24 requested changes
Suggested a few more changes. 

Additionally, please include the config script for ROS2 topic bridges when spawning the sensor model as discussed. Let me know if you need help with that!

2025-07-02 14:09 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/AcousticBeam.hh
If this part is from the upstreamed gz-sensor DVL code, can we not repurpose it rather than defining everything again?

2025-07-02 14:09 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/AxisAlignedPatch2.hh
Same as above

2025-07-07 19:28 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/AcousticBeam.hh
The DVL header file doesn't include this class, only the source code defines it, so I'm afraid we wouldn't be able to use it directly in our code. [DVL header file](https://github.com/gazebosim/gz-sensors/blob/gz-sensors9/include/gz/sensors/DopplerVelocityLog.hh)

2025-07-07 19:28 UTC, hmoyen commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/AxisAlignedPatch2.hh
DVL header also does not include this class

2025-07-07 20:59 UTC, rakeshv24 commented on gazebo/dave_gz_multibeam_sonar/multibeam_sonar/AcousticBeam.hh
Sounds good

2025-07-11 22:42 UTC, rakeshv24 reviewed
@hmoyen thanks for making the changes! I have a few more suggestions.

I'm not sure why but the point cloud does not show up for me. Any idea why?

Can you also include the sonar plugin to the BlueROV (to the front bottom of the vehicle) for demo purposes?

2025-07-11 22:42 UTC, rakeshv24 commented on models/dave_sensor_models/launch/upload_sensor.launch.py
While this is correct, please follow the same format as in [upload_robot.py](https://github.com/IOES-Lab/dave/blob/197359ecaf64f12f73f3f253728adc1466ae43b5/models/dave_robot_models/launch/upload_robot.launch.py) for consistency.

Make use of `PathJoinSubstitution` rather than the `os.path.join` . Also, `launch_setup` function is not required.

2025-07-15 16:17 UTC, hmoyen commented on models/dave_sensor_models/launch/upload_sensor.launch.py
Making the changes now. I used launch_setup because most sensor models don’t have a config file, only the multibeam sonar models do. I couldn’t find a clean way to handle the missing file during launch.

2025-07-15 16:18 UTC, hmoyen commented on models/dave_sensor_models/launch/upload_sensor.launch.py
About the point cloud, it's a difference between the topic names in the launch file and SDF model. I will correct it

2025-07-15 18:56 UTC, rakeshv24 reviewed
@hmoyen Can you include an example of the sonar plugin added to BlueROV2 for demo purposes?

2025-07-15 18:56 UTC, rakeshv24 commented on models/dave_sensor_models/launch/upload_sensor.launch.py
Oh okay, makes sense! I have made some changes as well - pushing now.

2025-07-16 05:59 UTC, hmoyen commented on models/dave_sensor_models/launch/upload_sensor.launch.py
I’ve added the BlueROV2 example, let me know if that's what you had in mind. I copied the `bluerov2_heavy` model and attached the plugin into the robot. I also created a new demo world with some cylinders to help test and visualize the results. The documentation has also been updated : [Wiki](https://dave-ros2.notion.site/Multibeam-Sonar-Plugin-223661362ab2803b873bda4878fc55a8).

2025-07-16 13:59 UTC, rakeshv24 commented on models/dave_sensor_models/launch/upload_sensor.launch.py
@hmoyen Rather than creating a new robot model for this example, it would be better to attach the sensor plugin to the existing `bluerov`, `rexrov`, and `bluerov2_heavy` as how the other sensors are attached. The purpose is to showcase the robots being spawned with full capability that includes all the important sensors on board.

Let me know if you need help with this.

2025-07-16 14:35 UTC, hmoyen commented on models/dave_sensor_models/launch/upload_sensor.launch.py
Okay! I will add to the `bluerov2_heavy` model then

2025-07-16 20:32 UTC, rakeshv24 approved these changes
@hmoyen Looks good to me!

One last thing we need to look at is:
"What happens if the machine doesn’t have CUDA installed? would it prevent from compiling with colcon build?"

2025-07-17 03:32 UTC, hmoyen commented
> @hmoyen Looks good to me!
> 
> One last thing we need to look at is: "What happens if the machine doesn’t have CUDA installed? would it prevent from compiling with colcon build?"

In the `multibeam_sonar` package CMake we have:

```
find_package(CUDAToolkit QUIET)
if(CUDAToolkit_FOUND)
...
else()
  message(STATUS "CUDA Toolkit not found: Skipping CUDA-specific targets")
endif()
```

Is it failing to build on non CUDA platforms?

2025-07-17 17:54 UTC, rakeshv24 commented
> > @hmoyen Looks good to me!
> > One last thing we need to look at is: "What happens if the machine doesn’t have CUDA installed? would it prevent from compiling with colcon build?"
> 
> In the `multibeam_sonar` package CMake we have:
> 
> ```
> find_package(CUDAToolkit QUIET)
> if(CUDAToolkit_FOUND)
> ...
> else()
>   message(STATUS "CUDA Toolkit not found: Skipping CUDA-specific targets")
> endif()
> ```
> 
> Is it failing to build on non CUDA platforms?

Yes, the build is still failing on non CUDA platforms. The `if` flag is not working as intended.

2025-07-17 18:19 UTC, rakeshv24 commented
@hmoyen Ready to merge! 🚀

2025-07-24 01:18 UTC, woensug-choi commented
@hmoyen Go a head and merge :D

2025-07-24 03:47 UTC, merged